# ----------------------------
# Makefile Options
# ----------------------------

NAME = FONTVIEW
ICON = icon.png
DESCRIPTION = "Font Hook Previewer"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
